version: "3.9"

services:
  cuentaCorrienteService:
    container_name: ms-cuenta-corriente
    image: ms-cuenta-corriente:0.0.1-SNAPSHOT
    ports:
      - "8083:8083"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    networks:
      - network_tp

networks:
  network_tp:
    driver: bridge